import React, { useState } from 'react';
import {
  FileText,
  CheckCircle2,
  ShieldCheck,
  UserCheck,
  Copy,
  Check,
  Download,
  RotateCcw,
  Layers,
  TrendingUp,
  AlertTriangle,
  Award,
} from 'lucide-react';

export function FinalResultView({ task, onOpenRevision }) {
  const [copied, setCopied] = useState(false);
  const output = task?.final_output || {};

  const handleCopy = () => {
    const text = `
# ${task.name}
${output.summary || ''}

## Executive Summary
${output.executive_summary || ''}

## Key Findings
${(output.key_findings || []).map((f) => `- ${f}`).join('\n')}

## Analysis
${output.analysis || ''}

## Strategic Recommendations
${(output.recommendations || []).map((r) => `- ${r}`).join('\n')}

## Risk Assessment
${(output.risks || []).map((r) => `- ${r}`).join('\n')}

## Key Assumptions
${(output.assumptions || []).map((a) => `- ${a}`).join('\n')}

## Governance Notes
${output.governance_notes || 'All governance policies passed.'}
    `.trim();

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const dataStr =
      'data:text/json;charset=utf-8,' +
      encodeURIComponent(JSON.stringify(task.final_output, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `${task.name.replace(/\s+/g, '_')}_final_report.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
      {/* Report Header & Action Bar */}
      <div className="px-6 py-4 border-b border-slate-200 bg-slate-50/60 flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h3 className="text-base font-bold text-slate-900">Executive Final Deliverable</h3>
            <span className="px-2 py-0.5 rounded text-[11px] font-semibold bg-emerald-100 text-emerald-800 border border-emerald-200">
              v{task.version || 1}.0 Final
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-0.5">
            Compiled and synthesized by specialized AI agents with governance audit trail
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-700 bg-white border border-slate-300 hover:bg-slate-50 rounded-lg shadow-2xs transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied!' : 'Copy Report'}</span>
          </button>

          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-700 bg-white border border-slate-300 hover:bg-slate-50 rounded-lg shadow-2xs transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export JSON</span>
          </button>

          {onOpenRevision && (
            <button
              onClick={onOpenRevision}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-brand-700 bg-brand-50 border border-brand-200 hover:bg-brand-100 rounded-lg shadow-2xs transition-colors"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              <span>Request Revision</span>
            </button>
          )}
        </div>
      </div>

      {/* Trust & Verification Badges */}
      <div className="px-6 py-3 bg-slate-50 border-b border-slate-200/80 flex flex-wrap items-center gap-4 text-xs">
        <div className="flex items-center gap-1.5 text-slate-700 font-medium">
          <Layers className="w-4 h-4 text-blue-600" />
          <span>
            Generated by {output.contributing_agents ? output.contributing_agents.length : 6} Specialized Agents
          </span>
        </div>

        <div className="flex items-center gap-1.5 text-emerald-700 font-medium">
          <ShieldCheck className="w-4 h-4 text-emerald-600" />
          <span>Governance Checkpoints Cleared</span>
        </div>

        {output.human_reviewed && (
          <div className="flex items-center gap-1.5 text-purple-700 font-medium">
            <UserCheck className="w-4 h-4 text-purple-600" />
            <span>Authorized by Human Executive</span>
          </div>
        )}
      </div>

      {/* Report Body */}
      <div className="p-6 sm:p-8 space-y-6 max-w-4xl">
        {/* Executive Summary */}
        <section className="p-4 rounded-xl bg-slate-50 border border-slate-200/80">
          <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2 flex items-center gap-2">
            <Award className="w-4 h-4 text-brand-600" />
            Executive Summary
          </h4>
          <p className="text-sm leading-relaxed text-slate-800 font-normal">
            {output.executive_summary || output.summary || 'Summary pending...'}
          </p>
        </section>

        {/* Key Findings Grid */}
        {output.key_findings && output.key_findings.length > 0 && (
          <section>
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-3 flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-emerald-600" />
              Strategic Key Findings
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {output.key_findings.map((finding, idx) => (
                <div
                  key={idx}
                  className="p-3.5 rounded-lg border border-slate-200 bg-white hover:border-slate-300 transition-colors shadow-2xs"
                >
                  <div className="flex items-start gap-2.5">
                    <span className="w-5 h-5 rounded-full bg-brand-50 text-brand-700 flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">
                      {idx + 1}
                    </span>
                    <p className="text-xs text-slate-700 leading-normal">{finding}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Detailed Analysis */}
        {output.analysis && (
          <section className="space-y-2">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500">
              Market & Operational Analysis
            </h4>
            <p className="text-xs text-slate-700 leading-relaxed bg-slate-50/50 p-4 rounded-lg border border-slate-200">
              {output.analysis}
            </p>
          </section>
        )}

        {/* Recommendations & Risks Columns */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-2">
          {/* Recommendations */}
          {output.recommendations && (
            <div className="space-y-3">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-700 flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                Actionable Recommendations
              </h4>
              <ul className="space-y-2">
                {output.recommendations.map((rec, i) => (
                  <li
                    key={i}
                    className="flex items-start gap-2 p-2.5 rounded-lg bg-emerald-50/40 border border-emerald-100 text-xs text-slate-700"
                  >
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 shrink-0 mt-1.5" />
                    <span>{rec}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Risk Factors */}
          {output.risks && (
            <div className="space-y-3">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-700 flex items-center gap-1.5">
                <AlertTriangle className="w-4 h-4 text-amber-600" />
                Evaluated Risks & Mitigations
              </h4>
              <ul className="space-y-2">
                {output.risks.map((risk, i) => (
                  <li
                    key={i}
                    className="flex items-start gap-2 p-2.5 rounded-lg bg-amber-50/40 border border-amber-100 text-xs text-slate-700"
                  >
                    <span className="w-1.5 h-1.5 rounded-full bg-amber-500 shrink-0 mt-1.5" />
                    <span>{risk}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>

        {/* Assumptions */}
        {output.assumptions && output.assumptions.length > 0 && (
          <section className="pt-2">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
              Underlying Modeling Assumptions
            </h4>
            <div className="p-3 bg-slate-50 border border-slate-200 rounded-lg text-xs text-slate-600 space-y-1">
              {output.assumptions.map((assump, idx) => (
                <div key={idx} className="flex items-center gap-2">
                  <span className="text-slate-400">•</span>
                  <span>{assump}</span>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Governance & Sign-Off Notes */}
        <section className="pt-4 border-t border-slate-200">
          <div className="p-3.5 bg-blue-50/50 border border-blue-200 rounded-lg flex items-start gap-3">
            <ShieldCheck className="w-5 h-5 text-brand-600 shrink-0 mt-0.5" />
            <div>
              <h5 className="text-xs font-bold text-slate-900">Governance & Compliance Audit Note</h5>
              <p className="text-xs text-slate-600 mt-0.5">
                {output.governance_notes ||
                  'This deliverable passed Compliance Agent verification, adherence checks against active organizational policies, and human authorization checkpoints.'}
              </p>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
